skip_tags: true
image: Visual Studio 2017
build:
  verbosity: detailed
build_script:
- cmd: dotnet restore ./src/repro.sln --disable-parallel -v n
- cmd: dotnet build ./src/repro.sln --disable-parallel -v n
- cmd: dotnet build ./src/repro.sln --disable-parallel -v n
- cmd: dotnet pack ./src/repro.sln --output ../../artifacts/
test: off
artifacts:
- path: ./artifacts/*