skip_tags: true
image: Visual Studio 2017
build:
  verbosity: normal
build_script:
- cmd: msbuild ./src/repro.sln /t:Restore
- cmd: msbuild ./src/repro.sln /t:Build
- cmd: msbuild ./src/repro.sln /t:Pack /p:PackageOutputPath=../../artifacts/
test: off
artifacts:
- path: ./artifacts/*